IAM_CATEGORY_UID = 3
SYSTEM_CATEGORY_UID = 1
NETWORK_CATEGORY_UID = 4
APPLICATION_CATEGORY_UID = 6
OTHER_CATEGORY_UID = 0

AUTHENTICATION_ACTIVITY_UID = 2
AUTHORIZE_SESSION_ACTIVITY_UID = 3
ENTITY_MANAGEMENT_ACTIVITY_UID = 4
PROCESS_ACTIVITY_UID = 7
NETWORK_ACTIVITY_UID = 1
DNS_ACTIVITY_UID = 3
BASE_EVENT_CLASS_UID = 0
APPLICATION_ERROR_UID = 8
APPLICATION_LIFECYCLE_UID = 2

AUTHENTICATION_LOGON_ID = 1
AUTHENTICATION_LOGOFF_ID = 2
AUTHORIZE_SESSION_ASSIGN_PRIVILEGES_ID = 1
ENTITY_MANAGEMENT_READ_ID = 2

PROCESS_ACTIVITY_LAUNCH_ID = 1
PROCESS_ACTIVITY_TERMINATE_ID = 2

NETWORK_ACTIVITY_OPEN_ID = 1
NETWORK_ACTIVITY_CLOSE_ID = 2
NETWORK_ACTIVITY_TRAFFIC_ID = 6

DNS_ACTIVITY_QUERY_ID = 1
DNS_ACTIVITY_RESPONSE_ID = 2
DNS_ACTIVITY_TRAFFIC_ID = 6
APPLICATION_ERROR_GENERAL_ID = 1
APPLICATION_LIFECYCLE_INSTALL_ID = 1
APPLICATION_LIFECYCLE_REMOVE_ID = 2
APPLICATION_LIFECYCLE_START_ID = 3
APPLICATION_LIFECYCLE_STOP_ID = 4
APPLICATION_LIFECYCLE_RESTART_ID = 5
APPLICATION_LIFECYCLE_ENABLE_ID = 6
APPLICATION_LIFECYCLE_DISABLE_ID = 7
APPLICATION_LIFECYCLE_UPDATE_ID = 8

DEVICE_TYPE_UNKNOWN_ID = 0
NETWORK_DIRECTION_UNKNOWN_ID = 0


def to_class_uid(category_uid: int, class_uid: int) -> int:
    return category_uid * 1000 + class_uid


def to_type_uid(class_uid: int, activity_id: int) -> int:
    return class_uid * 100 + activity_id
